version: '3.8'

services:
  homelab-gateway:
    image: docker.1ms.run/nginx:alpine
    container_name: homelab-gateway-nginx
    restart: always
    network_mode: host
    volumes:
      - ./conf.d:/etc/nginx/conf.d:ro
      - ./ssl:/etc/nginx/ssl:ro
